### ISSUE TITLE
Failed to install ai-transaction in Linux

### ISSUE THREAD

**Issue by longdafeng** [winlinvip/ai-translation#2]
OS: centos stream 8

```
(venv) [longda@mail bin]$ ls -lrt
total 32
lrwxrwxrwx 1 longda longda   16 Jul  3 12:19 python3 -> /usr/bin/python3
lrwxrwxrwx 1 longda longda    7 Jul  3 12:19 python -> python3
-rwxrwxr-x 1 longda longda  272 Jul  3 12:19 easy_install-3.6
-rwxrwxr-x 1 longda longda  272 Jul  3 12:19 easy_install
-rwxrwxr-x 1 longda longda  244 Jul  3 12:19 pip3.6
-rwxrwxr-x 1 longda longda  244 Jul  3 12:19 pip3
-rwxrwxr-x 1 longda longda  244 Jul  3 12:19 pip
-rw-r--r-- 1 longda longda 2218 Jul  3 12:19 activate
-rw-r--r-- 1 longda longda 2438 Jul  3 12:19 activate.fish
-rw-r--r-- 1 longda longda 1274 Jul  3 12:19 activate.csh
(venv) [longda@mail bin]$ cd ..
(venv) [longda@mail venv]$ ls
bin  include  lib  lib64  pyvenv.cfg
(venv) [longda@mail venv]$ cd ..
(venv) [longda@mail ai-translation]$ ls
LICENSE  README.md  player  requirements.txt  translate.py  venv  whisper
(venv) [longda@mail ai-translation]$ which pip3
~/work/repo/ai-translation/venv/bin/pip3
(venv) [longda@mail ai-translation]$ pip3 install -r requirements.txt
Collecting aiohttp==3.8.4 (from -r requirements.txt (line 1))
Exception:
Traceback (most recent call last):
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/commands/install.py", line 346, in run
    requirement_set.prepare_files(finder)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/req/req_set.py", line 381, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/req/req_set.py", line 557, in _prepare_file
    require_hashes
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/index.py", line 589, in _get_pages
    page = self._get_page(location)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/index.py", line 704, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/index.py", line 813, in get_page
    "Cache-Control": "max-age=600",
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/download.py", line 387, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 640, in send
    r = adapter.send(request, **kwargs)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 303, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 187, in proxy_manager_for
    **proxy_kwargs
  File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 44, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
pip._vendor.requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
```

**Comment by longdafeng** [comment]
How to resolve 
```
File "/home/longda/work/repo/ai-translation/venv/lib64/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 44, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
```

**Comment by longdafeng** [comment]
it works in the latest mac os with proxy
